# Generated by Django 5.0.8 on 2024-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeuso',
            name='nome_motorista',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
    ]
